{% set name = "pygwb" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygwb-{{ version }}.tar.gz
  sha256: 675da6be45411e39b0032913499de3189abcf2f3bc4e48ff3bd208f86d22fa1d

build:
  skip: true  # [win or py>=312]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - python
    - numpy
    - matplotlib-base
    - scipy >=1.8.0,<1.14.0
    - bilby >=1.4
    - gwpy >=3.0.4
    - astropy >=5.2
    - gwdetchar
    - gwsumm
    - pycondor
    - lalsuite >=7.3
    - loguru
    - json5
    - seaborn
    - pycbc

test:
  imports:
    - pygwb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.ligo.org/pygwb/pygwb
  summary: Lighweight python stochastic gravitational-wave background analysis pipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - a-renzini
